### ISSUE TITLE
Backend to-do list

### ISSUE THREAD

**Issue by PeiShang** [AlphaTac/AlphaTac-Backend#6]
### 1. Data warehouse solution
- [ ] Design a long-term solution for our data warehouse, considering extensibility, availability, and cost. 

- [ ] Research on price of Alibaba's MongoDB services, data server and other options.

### 2. Upcoming match events
- [ ] Data engine get upcoming match events( a tentative solution is to use web crawler)

- [ ] Data engine save events into database

- [ ] Web server send events to frontend

### 3. Data exaction
- [ ] DataEngine collects raw data from Open Dota API

- [ ] DataEngine extract required data from raw data source.

- [ ] DataEngine save processed data into database
